### ISSUE TITLE
Skaitļavārdu/lietvārdu dalījums.

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#10]
Vasarā korpusos un Tēzaurā tika mainīts dalījums pamata skaitļa vārdos / lietvārdos. Nepieciešams pārliecināties, vai šis dalījums ir atspoguļots leksikonā.

Jaunais dalījums:

- nosauc skaitu un ir veidojamas abas dzimtes = lokāms pamata skaitļa vārds (četri, pieci, seši, utt.)
- nosauc skaitu/apjomu, bet ir viena dzimte = lietvārds (nulle, puse, trešdaļa, desmits, pussimts, simts, pārsimts, tūkstotis, pusmiljons, miljons, miljards, biljons, triljons, kvardiljons, kvintiljons, pentiljons, sekstiljons, septiljons, oktiljons, noniljons, deciljons).

**Comment by PeterisP** [comment]
Bija gļuks ar to, ka lokāmie skaitļavārdi pieļāva sieviešu dzimtes formas, labots

**Comment by lauma** [comment]
Umm, lokāmie skaitļa vārdi pieļauj sieviešu dzimtes formas, jā, turklāt nu jau visi!

**Comment by PeterisP** [comment]
Tas bija par to, ka visiem tiem "simts", "miljons" utml bija atļautas sieviešu dzimtes formas
