### ISSUE TITLE
Verbu noliegumu lemmas

### ISSUE THREAD

**Issue by PeterisP** [PeterisP/morphology#102]
Izrunājām ar Lauru un @lauma ka noliegtajiem verbiem lemmas vajag bez nolieguma, kā ir UD standartā.

Jāizmaina kodā, tagset dokumentā un vienībtestos (piemēram https://github.com/PeterisP/morphology/blob/master/src/test/java/lv/semti/morphology/Testi/MorphologyTest.java#L801).   

Jāizmaina arī esošajā treebank marķējumā.

Jāpārtrenē tageris un jāpārtago lietas..

**Comment by lauma** [comment]
Vai mums nevajadzētu tomēr arī Guntas un Baibas viedokli, pirms maina? Vai tas ir pārāk pašsaprotami?

**Comment by PeterisP** [comment]
Viela pārdomām - ja šādi dara, tad ir skaidrs par automātiski atvasinātajiem noliegumiem, bet ko mēs daram ar tēzaura šķirkļiem, kas ir tikai/tieši noliegumā?   Viņiem tad šķirkļa vārds utt ir noliegts, tabulā ir tikai noliegums,smukā pamatforma ir noliegta un tikai morforīkos ir nenoliegta lemma? Varbūt jālieto to pašu "Pamatforma morforīkiem" karodziņu.

**Comment by lauma** [comment]
Vai mums ir tādi vārdi, kas ir tikai noliegumā? Ja ir, vai viņiem noliegumu vispār valodnieki vēl grib tagot morfotagā?

**Comment by PeterisP** [comment]
> Vai mums ir tādi vārdi, kas ir tikai noliegumā? Ja ir, vai viņiem noliegumu vispār valodnieki vēl grib tagot morfotagā?

Zem simta. 
nebūt, neaizmirst, neaizvērt, neapdomāt, neapmeklēt, neaptrūkt, neatbilst, neatklāt, nenoēsties, neblēņoties utt

**Comment by lauma** [comment]
Ja mums nav vārdu aizmirst vai blēņoties, tas ir jālabo tēzaurā. Bet vai mums ir pa īstam tādi, kam ir noliegums, bet pozitīvais tēzaurā nebūs liekams? Jo rīcība tādiem noteikti atšķirsies no rīcības tiem, kam skaidrošanas ērtības labad ir noliegtā daļa aprakstīta atsevišķā šķirklī.

**Comment by PeterisP** [comment]
Ar šķirkļiem kur ir noliegtie verbi, izlēmām darīt šādi:
1. ieliekam "pamatforma morforīkiem" laukā nenoliegto formu (lai tagotajā lemma ir nenoliegta) un pārējo atstājam kā ir;
2. pieprogrammējam tēzaurā lai pēc nolieguma formas meklētājā smuki atrod arī nenoliegto šķirkli (tam vajadzēs atsevišķu biļeti)
3. pamazām izkaujam noliegtos šķirkļus (tādi ir <100), pieliekot tos pie "pamatšķirkļa", ja nepieciešams ar atsevišķu nozīmi ar structural restriction

**Comment by PeterisP** [comment]
Trebank nomainīts, nākamajā tagerī būs; tēzaurā noliegtajiem karodziņi salikti. 

Jānotestē, vai tēzaurā pēc nolieguma formas smuki atrod nenoliegto šķirkli.

**Comment by lrituma** [comment]
Ja ir verbs, kam nav pretī nenoliegta verba, tad tam noliegumu nemarķē un lemma paliek ar visu -ne. nebēdņot, nebēdņoties. Baibas akcepts.
