### ISSUE TITLE
Turpmāks locīšana

### ISSUE THREAD

**Issue by PeterisP** [PeterisP/morphology#104]
Manu smadzeni salauza https://darbaversija.tezaurs.lv/turpm%C4%81ks, kā tas korekti jāloka?

Pašreiz tur absolūti nav pareizi, bet lai būtu pareizi, būtu jāsaprot, kāda tam ir pakāpe? Kāda tam ir vispārākā forma?

**Comment by lauma** [comment]
A kapēc nevar locīt kā īpašības vārdu, kam "turpmāk-" ir nelokāmā daļa tā kā vārdam "balts" "balt-"?

**Comment by lauma** [comment]
Visticamāk viņam nav pakāpju, jo viņš nenozīmē neko tādu, kam pakāpes veidot būtu adekvāti. Teorētiski varbūt ir jauki atpazīt, (noteikti ne ģenerēt) formu "visturpmākais", un lai to dabūtu tad būtu jāiezīmē, ka "turpmākais" ir pārākā pakāpe, bet nez vai tas ir korekti. @lrituma , kāda pakāpe jātago vārdam "turpmāks"?

**Comment by PeterisP** [comment]
> A kapēc nevar locīt kā īpašības vārdu, kam "turpmāk-" ir nelokāmā daļa tā kā vārdam "balts" "balt-"?

Locīt var visādi, jāsaprot kā vajag. Locīt kā "balts" nozīmētu ka ir "turpmāks" "turmpākāks" "visturpmākākais", kas šķiet dīvaini, tāpēc arī šis jautājums.

**Comment by lrituma** [comment]
ŠIs ir īpašības vārds, kuram šī forma ir veidojusies no pakāpes, bet nē, šobrīd šī ir pamata pakāpe, citas neveidojam un tabulā apakšā piezīmes par pakāpēm nerādam.  Līdzīga situācija ir ar vairāki - arī īpašības vārds un neviens tabulā nesaka, ka tur varētu būt pārākās pakāpes.
