### ISSUE TITLE
Analizatora pašdarbība ar īpašības vārdu pārākajām pakāpēm

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#106]
Saistībā ar https://gitlab.com/ailab/tezaurs/-/issues/217 ir jātiek galā ar pareizu šo vārdu locīšanu atbilstoši tēzaurā teiktajam
- pārāks (ir tikai pārākā un vispārākā pakāpe)
- pirmāks (ir viena pakāpe un tā saucas pamata)
- turpmāks  (ir viena pakāpe un tā saucas pamata)

Pašlaik analizators min, ka arī turpmāks ir pārākā pakāpe no turpms un tas ir neveikli.

**Comment by PeterisP** [comment]
ok, "pārāks" ir kaut kas jauns un par to ir jādomā, tas ir kaut kas pilnīgi cits nekā "pirmāks" gadījums, pat tieši pretēji - priekš "turpmāks" tieši izmainīju lai situācijā ja padotā lemma ir "xxxx-āks" viņš kā celmu paņem "xxxāk" nevis "xxx"; savukārt "pārāks" tieši kā celms ir jāņem "pār" lai būtu iespējams izveidot formu "vis-pār-āk-ais", tad man tas "turpms" risinājums atkal ir jāplēš ārā. grr.
