### ISSUE TITLE
49. paradigma Tēzauram

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#107]
Lūdzu uztaisīt tā, lai Locījumu serviss, ko lieto Tēzaurs, 49. paradigmai atgriež normālu, netukšu masīvu tāpat kā citām paradigmām, kam dažādu locīumu, jo šobrīd visi 49. paradigmas pārstāvji uz katru Tēzaura laidienu notrigero kļūdu nosacījumu, ka analizators nav mācējs ar viņiem neko izdarīt.

**Comment by lauma** [comment]
Nelokāmie apstākļa vārdi, partikulas un tamlīdzīgas lietas visas atdod masīvu ar tās vienas formas aprakstu, un tā ir labi. Vajag, lai tā ir arī 49. paradigmai.

**Comment by PeterisP** [comment]
Salabots ar https://github.com/PeterisP/morphology/commit/1c6e8bc0045bdc070ddc1205db15ac83e1c88086
