### ISSUE TITLE
Pustrīs dīvainumi

### ISSUE THREAD

**Issue by PeterisP** [PeterisP/morphology#113]
Citēju Baibu: N. pustrīs; Ģen. pustriju; D. pustrim, pustrijiem; A. pustrīs; L. pustrijos  
Bez sieviešu dzimtes

**Comment by PeterisP** [comment]
Jāieliek manuāli pēc https://gitlab.com/ailab/tezaurs/-/issues/365

**Comment by lauma** [comment]
Šis salabosies, kad tēzaurā ieviesiesīsies vārdformas.

**Comment by lauma** [comment]
Saliku, atstāju valodniecēm pārbaudīt, jo tas, ka nav sieviešu dzimtes, nešķiet pareizi.
