### ISSUE TITLE
Spēt ielasīt vārdšķiras tipu no tēzaura nozīmēm

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#115]
Darbības vārdiem un vietniekvārdiem vārdšķiras apakštips - attiecīgi modāls vai pamata un attieksmes, jautājamais, utt. - Tēzaurā var atrasties pie nozīmes, nevis pie leksēmas. Tas ļautu novienkāršot palīgleksikonā doto vietniekvārdu pierakstu - nevajadzētu 72 formas vārdam "kurš".

**Comment by PeterisP** [comment]
Vajadzētu tad tēzaurā tos apakštipus ieviest kā paraudziņus un vismaz dažiem vārdiem sarakstīt, savādāk es nevaru pat notestēt.

**Comment by lauma** [comment]
Ir jau. 
- https://darbaversija.tezaurs.lv/k%C4%81ds
- https://darbaversija.tezaurs.lv/kur%C5%A1:1

Kādu verbu, cerams, @lrituma var pateikt.

**Comment by PeterisP** [comment]
Darbības vārdiem vajag ieviest karogu. Morfopusē lieto šādas vērtības

<Attribute LV="Darbības vārda tips" EN="Verb type" PartOfSpeech="Darbības vārds" MarkupPos="1" Description="patstāvīgs vai palīg d.v ?">
	<Value LV="Patstāvīgs darbības vārds" EN="Main" Tag="m"/>
	<Value LV="Modāls" EN="Modal" Tag="o"/>
	<Value LV="Fāzes" EN="Phasal" Tag="p"/>
	<Value LV="Izpausmes veida" EN="Expression" Tag="e"/>
	<Value LV="Palīgverbs 'būt'" EN="'to be' as auxiliary or copula" Tag="c"/>
	<Value LV="Saitiņas 'tikt' un 'tapt'" EN="Other copulas" Tag="t"/>
	<Value LV="Palīgverbi 'tikt' un 'tapt'" EN="Other auxiliaries" Tag="a"/>
</Attribute>

**Comment by lauma** [comment]
Piemērs saikļiem - vai.

**Comment by PeterisP** [comment]
Darbības vārdu tipiem ir biļetes par karogiem https://gitlab.com/ailab/tezaurs/-/issues/339 ; tad kad realizēs,  arī jāieraksta tēzaura datos.

**Comment by lauma** [comment]
Tēzaura datus valodnieki ik pa brīdim papildina, bet programmiskā līmenī šis ir sataisīts jau pirms krietna laika.
