### ISSUE TITLE
Analizatora pašdarbība ar divdabju pakāpēm

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#119]
Baiba ziņo, ka sintakses korpusā ir pareizi, bet morfofaila kļūdu sarakstā teikts, ka jābūt pārākai vai vispārākai pakāpei. Neliekas labi, ņemot vērā, ka tam ir noteiktas formas tomēr. 
Piemēri:
beigta
kvalificēts
nebijušu
esošajās
pārsteigts
Visus vārdus pārbaudīju online servisā, visiem deva pamata pakāpes, izņemot "nebijušu" - tam vispār neparādās pakāpes ailīte.

**Comment by lauma** [comment]
Mēs secinājām, ka varētu būt jāpārbauda, vai šiem vārdiem ir pareizi notagota pagātne/tagadne.

Bet bubuļu fails šos savus iebildumus pauž nesaprotamā veidā, kas ir jālabo.

**Comment by PeterisP** [comment]
Jā, tur atšķirība ir 10. burtiņā, kas ir laiks (pagātne/tagadne); tas izskatījās pēc pakāpes jo pakāpe ir priekšpēdējais burtiņš bet tas reports pēdejos divus divdabja taga burtiņus vispār neņēma vērā jo to tageris netago. 
Nākamais fails būs ar smukāku/pilnāku tagu, kur tas būs skaidrāk redzams, bet šiem vārdiem būs jālabo to laiki (ja  -ts -ta ir norādīts tagadnes p nevis pagātnes s)
