### ISSUE TITLE
"Pēdējajo" locīšana

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#12]
Vajag autoritatīvo @VaBaiba viedokli par -jais īpāšības vārdu locīšanu:
Kuros locījumos kuriem īpašības vārdiem noteiktās formas veido nevis ar paplašināto galotni, bet īso? Pēdējajo vai pēdējo? Vai tas ir visiem īpašības vārdiem, kam nominatīvā not. galotnē ir izskaņa "-jais"? Abām dzimtēm? Kuros locījumos? Pieļaujamas ir abas formas vai tikai īsā?

**Comment by VaBaiba** [comment]
Gramatikas teic, ka dažiem noteiktajiem adjektīviem  nemēdz būt pilnas paplašinātās galotnes vsk. un dsk. datīvā un lokatīvā Tie ir adj. ar  izskaņu -ējais - pēdējais, pārējais, vakarējais, īpatnējais, ārkārtējais.
Ir vēl grupa, kam neiesaka paplašināto galotni, bet mēs negribētu aizliegt tādas formas kā "cienījamajai", "caurstaigājamā" u.tml.
Mani vakar nodarbināja līdzīga problēma ar vārdiem, kuru pamatforma ir ar noteikto galotni Tēzaura JSON. Tur bija vārdi: 
1) pērnais, pārējais, nākamais, pēdējais, galvenais, (gramatika s. -ā;); 
2)  turpmākais, galējais,  vienīgais, beidzamais,  nākošais (ar dažādām dīvainām gramatikām)

**Comment by VaBaiba** [comment]
Ja nu gadījumā Tev, Pēteri, nepatika mana atbilde, tad:
1) vārdiem - galējais, pēdējais, pārējais, vakarējais, īpatnējais, ārkārtējais - atšķiras vsk. un dsk. dat. un lok. (piem., pēdējais - pēdējam, pēdējā, pēdējiem, pēdējos). Nav tādu formu kā pēdējajam, pēdējajā, pēdējajiem, pēdējajos. Atpazīšanā var atpazīt tos pēdējajos, bet ģenerēt nevajag.
2) mēs domājam, ka pārējiem var palikt tā, kā ir.

**Comment by lrituma** [comment]
Noteiktajiem īpašības vārdiem ar ar izskaņu "-ējais" neveido paplašināto galotni ar "-aj-" datīva un lokatīva locījumos (kā arī dsk.instrumentālī, kas nozīmē nepaplašināto galotni vārdu savienojumos "ar "-ējo"").  Tageris šajos locījumos atpazīst šo vārdu kā nenoteiktu.
1) Vai tas nav iemesls, kāpēc tika izveidota nepareiza lemma "pēdējs"?
2) Vai gribam, lai tagā šajos gadījumos parādās nenoteiktība (kas būtu normāli, ņemot vērā, ka neliterārajā valodā parādās arī paplašinātās galotnes piemēri "pēdējajam"), kaut arī lemmā ir noteiktā galotne? Skatīt https://github.com/LUMII-AILab/Morphocorpus/issues/9.

**Comment by PeterisP** [comment]
Manuprāt done http://tezaurs.lv/#/sv/pēdējais

**Comment by lauma** [comment]
Jānočeko, lai ar "izgāšais" un "izgāšā" arī šis strādātu.

**Comment by PeterisP** [comment]
Izskatās ok.
