### ISSUE TITLE
"Pusapģērbies" paradigma

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#13]
Iespējams, ka mums vajag paradigmu, kurā ielikt Tēzaura vārdu "pusapģērbies".

@VaBaiba, vai vari uzrakstīt locījumu tabulu? Tas ir, pēc kādām pazīmēm lokās, kuras formas ir, kuras nav? Man trūkst pārliecības, vai "pusapģērbušamies" ir forma, ko mums vajadzētu ģenerēt. Atpazīt varbūt vajag.

**Comment by lauma** [comment]
Ja šī ir nenoteiktā galotne, tad ierosinu pēc līdzības ar 13., 14. paradigmu iekļaut abas dzimtes vienā paradigmā.

**Comment by VaBaiba** [comment]
**Ģenerējamie**
vsk.
N pusapģērbies zēns / pusapģērbusies meitene
Ģ - / pusapģērbušās meitenes
D - / -
A pusapģērbušos zēnu / pusapģērbušos meiteni
L - / -
dsk.
N pusapģērbušies zēni / pusapģērbušās meitenes
Ģ pusapģērbušos zēnu / pusapģērbušos meiteņu
D - / -
A pusapģērbušos zēnus / pusapģērbušās meitenes
L - / -

**Analizējamie**
vīr. dz. vsk. Ģ piecēlušās zēna
vsk. L pusapģērbušā/pusapģērbušajā zēnā / pusapģērbušā/pusapģērbušajā meitenē
dsk. D pusapģērbušamies zēniem / pusapģērbušamies meitenēm
dsk. L pusapģērbušos/pusapģērbušajos zēnos / pusapģērbušās/pusapģērbušajās meitenēs

Izskatās pēc "jomajo"!

**Comment by PeterisP** [comment]
@VaBaiba - Kāda vārdšķira? Īpašības vārds? Vai tagā vēl kādi citi īpaši atribūti jāliek?

**Comment by PeterisP** [comment]
Ir paradigma #43 ar pagaidām vienīgo vārdu "pusapģērbies", bet tā kā ir totāls jomajo tad jāskatās kā notestēt - pielikt tēzaurā kādiem vārdiem tās paradigmas un padzenāt, kad noapdeitošu webservisu uz šo versiju.

**Comment by lauma** [comment]
Man jāsaliek tad Tēzaurā vēl kādiem vārdiem šī paradigma.


Lauma

**Comment by PeterisP** [comment]
Manuprāt ir ok http://tezaurs.lv/#/sv/pusapģērbies
