### ISSUE TITLE
"Jauniznācis" paradigma

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#14]
Iespējams, ka mums vajag paradigmu, kurā ielikt Tēzaura vārdus "jauniznācis", "pusaizaudzis", "pusjucis" .

@VaBaiba, vai vari uzrakstīt locījumu tabulu? Atkal norādot, kuras forma vajag gan atpazīt, gan ģenerēt (gramatiskas), un kuras - tikai atpazīt (negramatiskas, bet plaši lietotas).

Domāju, ka pēc līdzības ar 13. un 14. paradigmu, šai paradigmai jāiekļauj abas dzimtes.

**Comment by VaBaiba** [comment]
Ģenerējamie (nenot. // not.)
vsk.
N pusjucis zēns / pusjukusi meitene // pusjukušais zēns / pusjukusī meitene
Ģ pusjukuša zēna / pusjukušas meitenes // pusjukušo zēnu / pusjukušo meiteņu
D pusjukušam zēnam / pusjukušai meitenei // pusjukušajam zēnam / pusjukušajai meitenei
A pusjukušu zēnu / pusjukušu meiteni // pusjukušos zēnus / pusjukušās meitenes
L pusjukušā zēnā / pusjukušā meitenē // pusjukušajā zēnā / pusjukušanā meitenē  
dsk.
N pusjukuši zēni / pusjukušas meitenes // pusjukušie zēni / pusjukušās meitenes
Ģ pusjukušu zēnu / pusjukušu meiteņu // pusjukušo zēnu / pusjukušo meiteņu
D pusjukušiem zēniem / pusjukušām meitenēm // pusjukušajiem zēniem / pusjukušajām meitenēm
A pusjukušus zēnus / pusjukušas meitenes // pusjukušos zēnus / pusjukušās meitenes
L pusjukušos zēnos / pusjukušās meitenēs  // pusjukušajos zēnos / pusjukušajās meitenēs

Pagaidām nevaru iedomāties, ko vēl analizēt.

**Comment by PeterisP** [comment]
Paradigmu var izveidot. @VaBaiba - kā šādus tagojam? Kā īpašības vārdus? Vai pieļaujam pārāko un vispārāko formu?

**Comment by PeterisP** [comment]
Paradigmas nr. 42

**Comment by VaBaiba** [comment]
Tagojam kā īpašības vārdus, bet salīdzināmās pakāpes nevajadzētu ģenerēt - pārāk dīvainas leksiskās nozīmes viņiem sanāk. 
Tātad atpazīt var arī: pusjukušāks / pusjukušāka // vispusjukušākā / vispusjukušākais.

**Comment by PeterisP** [comment]
Manuprāt viss ok http://tezaurs.lv/#/sv/jaundzimis
