### ISSUE TITLE
griezt -> gried! griediet!

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#15]
No Tezaurs.lv ir ienākusi sūdzība, ka http://tezaurs.lv/#/sv/griezt/1 un http://tezaurs.lv/#/sv/atgriezt/1 ir pavēles izteiksmes formas attiecīgi gried/griediet un atgried/atgriediet. Vismaz pirmajā acu uzmetienā šķiet, ka Tēzaurs paradigmu un celmus padod pareizus, tātad problēma varētu būt morfoloģiskajā mijā mijā.

Tāda pati problēma ir arī vārdiem mēzt, bliezt, vēzt un, iespējams, visiem, kam stem1, stem2, stem3 ir attiecīgi `.*[aeiouāēīū]z`, `.*[aeiouāēīū]ž`, `.*[aeiouāēīū]z`.

**Comment by PeterisP** [comment]
Kad nopublicēšu nākamo relīzi, jāpārtestē

**Comment by lauma** [comment]
Kad izmaiņas nokļūs līdz Tezaurs.lv?

**Comment by PeterisP** [comment]
Done, morfoloģijas 1.0.9 šis un viskautkas cits ir done, ir uzlikti arī jaunie webservisi.
