### ISSUE TITLE
"es vajagu" vai "nevajagu".

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#16]
Verbam "vajadzēt" nevajag ģenerēt Tēzaurā un nevienā citā ģenerācijas lietojumā pilnu paradigumu. "es vajagu", "tu vajagi" ir sviests. @lrituma, @VaBaiba, lūdzu, pasakiet precīzi, ko vēl nevajag.

**Comment by lauma** [comment]
Vai ir vēl kādi vārdi, kam ir līdzīgi formu ierobežojumi?

**Comment by PeterisP** [comment]
Prasās mehānisms hardcoded leksēmu tabulā, kur norādīt izņēmumformas, kuras pēc likumsakarībām derētu, bet vienkārši netiek lietotas (attiecīgi neģenerēt).

**Comment by lauma** [comment]
Es pašlaik ieliku Tēzaura javaskriptā ierobežojumu uz dažām formām, bet tas ir drausmīgi brutāls risinājums turklāt vietā, ko mēs taisamies izmest :/

Vēl es iedomājos, ka "es vajagos" neder tāpat kā "es vajagu", bet "es ievajagos" jau der.
