### ISSUE TITLE
31. paradigma

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#17]
Tēzaurs prasa morfoloģijai "ragus" un "pelus" ar 31. paradigmu un karodziņu par šķirkļavārdu daudzskaitli (analoģiski kā "ļaudis") un pretīm saņem pilnīgu neko.

**Comment by lauma** [comment]
Drošības pēc izprasīju arī 31. paradigmas locīšanas tabulu:

Vsk.
Dace Markus, Daces Markus, Dacei Markui, Daci Marku, Dacē Markū.

Dsk.
māsas Markus, māsu Marku, māsām Markūm, māsas Markus, māsās Markūs

Vokatīvs vienskaitlī ir "Markus!" vai "Marku", daudzskaitlī "Markus!"

**Comment by PeterisP** [comment]
http://api.tezaurs.lv/v1/inflections/pelus?paradigm=31&inflmisc=Sievie%C5%A1u_dzimte,Daudzskaitlis

atgriež [[]], jālabo

**Comment by lauma** [comment]
Savukārt http://api.tezaurs.lv/v1/inflections/pelus?paradigm=31&inflmisc=Sievie%C5%A1u_dzimte (bez daudzskaitļa karodziņa) rāda nepareizu daudzskaitļa nominatīvu, lokatīvu un vokatīvu.

Varbūt problēma ir tajā, ka pilnā tabula nesmaz nesatur daudzskaitļa nominatīvu formā "pelus", un tāpēc neko tādu nevar atlasīt.

Šā vai tā, 31. paradigmas daudzskaitļa tabula nav pareiza.
