### ISSUE TITLE
Iešanas vajadzības izteiksme

### ISSUE THREAD

**Issue by VaBaiba** [PeterisP/morphology#23]
Kāds sūdzas par vajadzības izteiksmes formu "jāaizej" (http://tezaurs.lv/#/sv/aiziet/1). Tādu piedāvā arī citiem vārdiem, kam pamatvārds ir "iet" (iet, aiziet). Vēl trakāk - "paiet" piedāvā tikai "jāpaej" (http://tezaurs.lv/#/sv/paiet).
Vajadzības izteiksme joprojām ir "jā-" + 3. personas forma.

Un vēl - tas it ok, ka mēs nekārtnos darbības vārdus saucam par 1. konj.? Tas tāds filozofisks jautājums.

@PeterisP @lauma

**Comment by lauma** [comment]
Par nekārtnajiem ir viena jocīga piebilde:
 Gudrās grāmatas parasti saka, ka nekārtnie darbības vārdi ir "iet", "būt" un "dot", taču pēc tā kā uzbūvēta morfoloģija, "dot" iekļaujas 1. konjugācijas triju celmu sistēmā un viņam neko speciālu nevajag. Tikai "iet" un "būt" sanāk tādi, kam vajag nestandarta apstrādi. Līdz ar to no "kā tas strādā" viedokļa "būt" un "iet" ir vairāk jēga norādīt nekārtnumu, savukārt, pie "dot" tas sanāktu tīri tradīcijas dēļ.

**Comment by lauma** [comment]
Paskatījos, kas notiek Tēzaura datos/webā - iespējams, ka problēma ir tajā, ka "iet" locīšana tiek saukta kā jebkura cita 1.konj. verba locīšana... @PeterisP, vai kaut kas ir mainījies un tā vairs nevajag darīt? Tur var pielikt kādu karogu vai savu paradigmu, vai nez ko.

**Comment by PeterisP** [comment]
Verbam "iet" šajā struktūrā sanāk 2 izņēmumformas (3. pers tagadne un vajadzības izteiksme). 

Lai tas būtu arī visiem atvasinātajiem verbiem "paiet" "aiziet" utt, man vajag arī tiem visiem tiem pielikt šīs izņēmumformas.

Risināt strukturēti mijā laikam nav iespējams - "saiet" un "smiet" fundamentāli atšķiras tieši(tikai?) tajās formās.

**Comment by PeterisP** [comment]
kaut arī varbūt var - pēc 3. celma beigām ..gāj var.

Lai mēs tos visus nesauktu par 1. konj var atbilstošajām leksēmām vienkārši datos pielikt karodziņu "Konjugācija":"Nekārtns" un tas nonāks visur, kur vajag.
