### ISSUE TITLE
Nolemtas vairāku adverbu lemmas un pakāpes pazīme

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#26]
1. sen, maz, drīz  - šai pamatformai tagā jābūt norādītai pamata pakāpei (otrā pozīcija)
2. daudz, vairāk, visvairāk - lemma "daudz", pakāpes attiecīgi pamata, pārākā, vispārāka.  Līdz ar to teksta analīzē gan "vairāk", gan "daudzāk", gan "visvairāk", gan "visdaudzāk" lemma būtu "daudz", bet paliekam pie tā, ka ģenerē tikai "vairāk" (pārākā) un "visvairāk" (vispārākā).
3. pārāk - lemma "pārāk", pakāpes nav, r0q 
Saistītā biļete [https://github.com/LUMII-AILab/Treebank/issues/71](url)

**Comment by PeterisP** [comment]
Kaut kā jādabū šī informācija iekšā tēzaurā.

**Comment by PeterisP** [comment]
Notestēju visus piemērus, darbojas, acīmredzot sen salabots.
