### ISSUE TITLE
Kļauzu reports

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#27]
Lūdzu, iekļauj meitenēm paredzētajā kļauzu reportā vārdus, kas marķēti kā np.* bet, kam lemma nav ar lielo burtu un pārējiem maziem.

Es nezinu, vai kaut kādi Abah-Klumpuri mums ir viens vai vairāki vārdi. Ja viens, nu tad tas arī ir derīgs lielo burtu lietojums, bet "BALTIJA" un "latvija" nav.

**Comment by PeterisP** [comment]
Protams, ka tādu ir čupa, pāri 200:

[lemmas.txt](https://github.com/PeterisP/morphology/files/1835330/lemmas.txt)

**Comment by lauma** [comment]
Tu turpmāk arī šitādus meitenēm dosi, šito biļeti var taisīt ciet?

**Comment by PeterisP** [comment]
Jā, tas ir pievienots MorphoEvaluate korpusa testam, turpmāk pamanīsies automātiski.
