### ISSUE TITLE
Atsevišķa paradigma būt-nebūt-pabūt-sabūt-utt

### ISSUE THREAD

**Issue by PeterisP** [PeterisP/morphology#30]
Paradigma nr 50

Jāpārnes dati no hardcoded tabulām, jānotestē

**Comment by PeterisP** [comment]
... jāsaprot, vai nevajag kādus no standarda divdabjiem šai paradigmai neveidot

**Comment by PeterisP** [comment]
Pagaidām par divdabjiem:

no -ts -ta atstāta tikai viena forma "būts" ("tur ir būts") ciešamajai kārtai, bet viss pārējais ārā
-šana ("laba būšana") atstāts
-dams -dama atstāts
-ošs -oša  ("tur esošas", "tur visesošākajiem") atstāts
-ams -ama ("esams" ????) ārā
-is -usi ("bijusī" "bijušāks" utt) atstāts

**Comment by lauma** [comment]
Latviešu valodā ir septiņi divdabji vēl bez -šana lietvārdiem. Vēl ir 2 nelokāmie:
-ot ("esot mājās") - ir
-am ("manīju viņu esam mājās") - liekas, ka ir.

**Comment by lauma** [comment]
Mums vajag 3. personas pagātnes formu "bij", lai izmetot šķirkli http://tezaurs.lv/#/sv/?bij nekas nepazūd.

**Comment by PeterisP** [comment]
2.0.5 relīzē (kas vēl top) izskatās ka būs
