### ISSUE TITLE
Verba otro pozīciju tagot pēc konteksta

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#31]
Kaut kad  kolēģes, kas lieto korpusu, sūdzējās, ka otrā pozīcija nav tagota dažādi pēc konteksta, bet tas ir ļpti būtiski, lai "būt" netago tikai kā palīgverbu vai tikai kā patstāvīgu vārdu, tāpat arī "tikt" mēdz funkcionēt gan kā palīgverbs, gan kā patstāvīgs verbs. Un tā vēl.

**Comment by PeterisP** [comment]
Tagerī ieslēgts laikam kopš 2.0 relīzes.
