### ISSUE TITLE
Teikumu tokenizācija

### ISSUE THREAD

**Issue by aznotins** [PeterisP/morphology#33]
Teikumi tiek neprecīzi tokenizēti uz biežiem saīsinājumiem ar punktu, vairāku līmeņu numerāciju un vairākām secīgām pieturzīmēm (tipiski ar pēdiņām un iekavām). Vairāku pieturzīmju gadījumā rodas nevēlams rezultāts - otrā pieturzīme tiek pievienota nākamā teikuma sākumā.

Piemēri:
```
4.1. tabula

Liels paldies! (Aplausi.)

(Ienāk istabā.) Nevajag tur piekopt?

(No zāles dep. A.Lejiņš: "Pareizi!")

ap 4000 g. p.m.ē.

Bateman et al., 2010
```

Pašreizējā tokenizācija (teikumi atdalīti ar jaunu rindkopu, vārdi - ar atstarpi):
```
4.1 .
tabula Liels paldies !

( Aplausi .
)

( Ienāk istabā .
) Nevajag tur piekopt ?

( No zāles dep .
A. Lejiņš  : " Pareizi !
" )

ap 4000 g.  p. m .
ē .

Bateman  et al .
, 2010
```

Vēlamais rezultāts:
```
4.1. tabula

Liels paldies !
( Aplausi . )

( Ienāk istabā . )
Nevajag tur piekopt ?

( No zāles dep. A.Lejiņš : " Pareizi ! " )

ap 4000 g. p.m.ē.

Bateman et al. , 2010
```

Citi bieži saīsinājumi ar punktu, ko vajadzētu iekļaut izņēmumu sarakstā:
```
u.c.
t.s.
u.tt.
u.t.t.
```

**Comment by PeterisP** [comment]
2.0.4 satur aprisinājumu "4.1. tabula" problēmai un risinājumu pārējām.
