### ISSUE TITLE
Loading Lexeme by ID doesn't work

### ISSUE THREAD

**Issue by soshial** [PeterisP/morphology#37]
I tried to use function calls, as you mentioned [here](https://github.com/LUMII-AILab/Tezaurs/issues/2#issuecomment-288578434):

        Analyzer analyzer = new Analyzer(true);
        Lexeme lexeme = analyzer.lexemeByID(43716);
        List<Wordform> wordforms = analyzer.generateInflections(lexeme);

The returned lexeme is `null`. What did I do wrong? Thank you, @PeterisP !

**Comment by PeterisP** [comment]
From 2.x we're switching to a lexicon automatically derived from tēzaurs.lv data export - the current default lexicon setup (Lexicon_v2.xml) does not have a lexeme with ID 43716.

Explicitly loading the old lexicon (`new Analyzer("Lexicon.xml";`) might work.

**Comment by soshial** [comment]
Thanks for the explanation. I took the lexeme ID from [here](http://api.tezaurs.lv:8182/v1/analyze/json/cilv%C4%93ks) (this is probably lexicon v2) and tried with both `Lexicon.xml` and `Lexicon_v2.xml`?

**Comment by soshial** [comment]
When will this switching to v2 happen? Is [web functionality](http://api.tezaurs.lv:8182/v1/analyze/json/cilv%C4%93ks) of the same version & database, that this morphology library has at the moment?

For example, your `/analyze/` API and Java `analyzer.analyzeLemma(...)` provide different results. The web API doesn't have some simple words like "kino", "atelje", "spēlētājs".

Also, will this library give information if a verb is of _pabeigta/nepabeigta veida_?

**Comment by lauma** [comment]
_Pabeigtība_ in Latvian is not a verb feature to be easely derived  from morphological elements like endings and infixes, so even if it were there (I doubt it), you should not trust it or use it.

**Comment by soshial** [comment]
I clearly understand that. There is other information that cannot be derived from word form only:

- Īpašvārds vs Sugas vārds
- Transitivitāte
- Īpašības vārda tips
- Apstākļa vārda tips

but this information is in the lexicon though. That is why I am asking this question: does this information exist anywhere at all (some dictionaries)?

**Comment by lauma** [comment]
Some of the Tēzaurs sources contains transitivity, see "trans." or "intrans." near the head of verb entries. Also for transitivity there are more or less strightforward syntactical check - transitivity basically mean, if verb can be used together with object:
- _dzert **alu**_, _lasīt **grāmatu**_ - OK, 
- _spēlēties **...**_ - not OK,
- _gulēt **... miegu? ...**_ - only rarely.

Meanwhile _pabeigtība_ in Latvian is much more fuzzy and vague than transitivity, thus, I don't think it will end up in Tēzaurs. As some languages has morphological distinction for that, linguists of the world do speak of such feature, but for Latvian it is purely semantical.

Types of adverbs and adjectives, I think, mostly comes from grammar books, where it mostly goes like one type can be enumerated and all the rest goes in other type. As tagset used in korpuss.lv requires this feature, Tēzaurs probably will eventually become augumented with it.

When it comes to proper/common nouns: well, traditional dictionaries like LLVV or MLVV just do not include proper nouns. Tēzaurs sometimes contains markings "vietv." or "persv.", e.g., http://tezaurs.lv/#/sv/Liepa, but as it is with all the things in the Tēzaurs - coverage is partial. The same as with adjective/adverb type, some augumentation eventually will be done, but I don't know when or to what extent yet. For now quite telling is the usage of capital letters in the entryword - if it contains at least one capital letter anywere, it is either some abbrievation or proper noun, but not your average common noun.

**Comment by soshial** [comment]
Thank you very much. I didn't know that the information that I put in the list, wasn't fully added to tezaurs. Is it possible to add _pabeigtība_ as a parameter, so that maybe I can try to add it to some verbs? I think I might have an idea how to do that not manually.

**Comment by lauma** [comment]
Umm, how do You plan to obtain such info? Usually even linguists strugle to assign _pabeigtība_ unambiguously.

**Comment by lauma** [comment]
I'm not convinced:
1) translation never happens one word <-> one word, it is always about matching some subset of the whole possible meanings each word in each language can have, and if some word in Russian has *morphologically* marked perfect, it does not mean all the meanings of "corresponding" Latvian verb will feature finished action *semmantically*.
2) various prefixes and verb/participle forms can impact perfect/imperfect,
3) generally perfect/imperfect is just a feature Latvian just do not have - the same way as Latvian has exactly two grammatical genders, while Russian has three, the same way as Latvian has some verb tenses Russian don't etc, thus, the applicability of such annotation is very limited.

**Comment by soshial** [comment]
Thank you for your explanation. I will try to accept the fact that this parameter is much more ephemeral in Latvian, than in Slavic languages. Nevajag to likt Prokrusta gultā =D

But in some cases, like "izdarīt" we can always say that it is used only as perfective, isnt it?

**Comment by soshial** [comment]
Returning to the original question I eventually got it to work (even with being weird that this nethod demands lemma explicitly, while lexeme must contain it):

`List<Wordform> wordforms = analyzer.generateInflections(lexeme, lexeme.getValue("Pamatforma"));`
