### ISSUE TITLE
Sentence splitting: a failing test case

### ISSUE THREAD

**Issue by normundsg** [PeterisP/morphology#39]
> Desmito vietu nopelnīja grupas " Very Cool People " kopā ar " Edavārdi " , Ansi un Kristīni Prauliņu izpildītā " Pa apli " , 11. pozīciju izcīnīja Markus Rivas " Nevaru tā " un 12. vietā ierindojās grupas " Astro ’ n ’ out " dziesma " Dejot trakāk " .

gets split into

> Desmito vietu nopelnīja grupas " Very Cool People " kopā ar " Edavārdi " , Ansi un Kristīni Prauliņu izpildītā " Pa apli " , 11. pozīciju izcīnīja Markus Rivas " Nevaru tā " un 12. vietā ierindojās grupas " Astro ’ n ’ out "

and

> dziesma " Dejot trakāk " .

without any "obvious" reason.

**Comment by PeterisP** [comment]
Vēsturisku iemeslu dēļ ir paredzēts, ka ja ir >50 tokenu, tad mēģina atrast puslīdz derīgu vietu (piemēram pēc jebkādas pieturzīmes) un pāršķelt.

Garuma limitu var pie metodes izsaukšanas padot arī lielāku; varbūt arī ir laiks pacelt defaulto, ja mums vairs parseriem un anotēšanas rīkiem nav tik liela sāpe ar hipergariem teikumiem.

**Comment by normundsg** [comment]
@aznotins nlp-pipe izsaukumā šobrīd laikam nav iespēja padot šo parametru?

@lauma interesanti būtu izvilkt no LVTB teikumu garuma sadalījumu (biežumsarakstu).

**Comment by normundsg** [comment]
Pārrunāju situāciju ar Laumu un valodniecēm. 50 tokenu limits ir radījis negatīvas sekas treebank rindkopu atlasē, jo rindkopas ar ar garākiem teikumiem netiek iekļautas treebank - pārāk liels čakars salikt atpakaļ sadalītos teikumus.

Optimāls noklusētais limits varētu būt 200 tokeni - esot ļoti daudz teikumu, kas garāki par 50, bet maz, kas garāki par 200.

Vēl viens variants būtu, ka pēc noklusēšanas nav nekāds ierobežojums (vai tas ir nereāli liels), un tikai tad, ja kādam rodas apstrādes problēmas, tad katram pašam jāspēlējas ar šo parametru.

**Comment by PeterisP** [comment]
Analizatorā noklusētais ir 250 (https://github.com/PeterisP/morphology/blob/master/src/main/java/lv/semti/morphology/analyzer/Splitting.java#L34)

Tagerī konfigurējams ar komandrindas parametru, noklusētais arī 250 https://github.com/PeterisP/LVTagger/blob/master/src/main/java/lv/lumii/morphotagger/MorphoPipe.java#L64
