### ISSUE TITLE
Šitais un šitas tēzaurā bez tabulas

### ISSUE THREAD

**Issue by PeterisP** [PeterisP/morphology#40]
https://tezaurs.lv/#/sv/%C5%A1itas

un 

https://tezaurs.lv/#/sv/%C5%A1itais

morfoloģijā neuzrāda tabulas, jāsaprot, kāpēc

**Comment by lauma** [comment]
Varbūt šo vārdu nav leksikonā un tāpēc Analizators nezina, kā taisīt tiem locījumus? Es no Tēzaura slēgtajām vārdšķirām locījumus nekādā veidā neimportēju, tur nāk tikai "šitas" un "25".
