### ISSUE TITLE
Pielikt leksikonā nelokāmu skaitļa vārdu trīs

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#41]
Skaitļa vārdam trīs ir lokāma versija un nelokāma versija, kas jebkurā locījumā var parādīties - trim vīriem / trīs vīriem.

**Comment by lauma** [comment]
Kā tagos nominatīvu - trīs vīri? Kā lokāmu vai nelokāmu?

**Comment by PeterisP** [comment]
Man šis apraksts neiet kopā ar treebank samarķēto `trīs m__mpg`. 

Ja ir nelokāma versija, tad tai nebūtu jābūt `trīs mcs0p0` (visos locījumos vienādi) kā vārdam `simt` ?
`trīs m__mpg` būtu tad, ja lokāmajai versijai būtu alternatīva ģenitīva forma trim/trīs.

**Comment by lrituma** [comment]
Jā, pārbaudīšu kokos marķējumu "trīs". Nezinu, ko darīsim ar akuzatīvu - tur gan lokāmajam trīs gan nelokāmajam ir viena forma.

**Comment by lauma** [comment]
Man šķita, ka akuzatīvs lokāmajam _trīs_ ir _trijus_, bet Laura tikko konstatēja, ka gramatika par šādu formu klusē.

**Comment by PeterisP** [comment]
Šķiet, ka sen salabots - ir vienībtests https://github.com/PeterisP/morphology/blob/master/src/test/java/lv/semti/morphology/Testi/MorphologyTest.java#L3469
