### ISSUE TITLE
"šķist" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#43]
Tageris nepiedāvā variantu palīgverba nozīmē un funkcijā lietotam "sķist", kur otrā pozīcija būtu t - vt.*

**Comment by PeterisP** [comment]
Tur tiešām vajag *t* nevis o vai p ?  tajā kategorijā mums ir tikai tikt, tapt, kļūt, palikt.

**Comment by lrituma** [comment]
Tur ir jābūt vt.. - saitiņas funkcijā ir tikt, tapt, kļūt un citi - šķist ir viens no citiem. "Viņa šķiet skaista." Šajos gadījumos.
