### ISSUE TITLE
īpašības vārda "vērts" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#45]
Netiek atpazīts un piedāvāts variants tagot "vērts" kā īpašības vārdu, Tezaurā ir atsevišķs šķirklis. Tas ir homonīms verba "vērt" formai, nevis viedots no tās.

**Comment by lauma** [comment]
Konteksts: lieta ir miljonu vērta, tas ir pilnīgi citādi nekā, ja lieta ir [iz]vērta caur adatas aci.

**Comment by PeterisP** [comment]
Tāpat kā #42 , morfoloģijā jāielādē jaunā tēzaura versija, tur aizkavēšanās ar DB pieeju
