### ISSUE TITLE
"vairāki" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#47]
Tezaurā norādīts, ka īpašības vārds, korpusā arī, morfotageris piedāvā vietniekvārda tagu (reports no 22.maija)

**Comment by PeterisP** [comment]
Interesanti, ka man ir īpašs unittest par šo vārdu
        // 2011-12-29 "vairāki" analizē kā skaitļa vārdu, vajag kā vietniekvārdu
        // vietniekv., nenoteiktais, nav personas, vīr.dz., daudzsk., nominatīvs, nav noliegtais

Tad mēs viņam vietniekvārda kandidātu ņemam ārā?

**Comment by lauma** [comment]
Man nav pareizās atbildes. Šis ir īstens Valodnieciskais Jautājums (TM). No tehniskā viedokļa tas vārds vislabāk iederas vietniekvārdu klasē, jo viņam nav noteikto galotņu, viņam nav vienskaitļa, un vispār, priekš īpašības vārda viņam ārkārtīgi daudz kā nav, bet cik atceros, man negribēja šito dot.

**Comment by lrituma** [comment]
Latviešu valodas gramatikā tas ir nosaukts par kvantitatīvas nozīmes īpašības vārdu, kuram līdzīgi kā daudzskaitliniekiem piemīt nepilna paradigma. Ja to saka gramatika, abas vārdnīcas - llvv un mlvv, tad es domāju, ka mēs turamies pie teorijas.

**Comment by PeterisP** [comment]
Sen atrisināts, tageris arī liek kā īpašības vārdu http://api.tezaurs.lv:8182/morphotagger/vair%C4%81ki%20puikas%20nav%20jauki.
