### ISSUE TITLE
"uzvarētājs" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#48]
Tageris peidāvā tikai verbu uzvarētājt. Kāpēc nemin lietvārdu?

**Comment by lauma** [comment]
-jt vispār neizklausās pēc leģitīmas minēšanas izskaņas, ne? Nu, 2. un 3. konjugācijai pirms -t vajadzētu būt patskanim piedēklim un 1. konjugāciju vismaz agrāk neminēja, jo tie vārdi ir praktiski visi uzskaitīti (it īpaši pēc Tēzaura veco un reto dīvainīšu pielikšanas).
