### ISSUE TITLE
"nespēt" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#51]
Pēc morfokļūdu saraksta no 22..05. nesaprotu, kas nav paticis šī verba tagošanā.

**Comment by lauma** [comment]
Uzmetu aci, pašlaik tēzaurā "spēt" izskatās labi, un "nespēt" nav (un labi, ka tā!).

**Comment by lrituma** [comment]
Jāparedz otrā pozīcija potenciāli p, ne tikai m

**Comment by PeterisP** [comment]
Mums kādu brīdi atpakaļ liktajā sarakstā 'nespēt' ir kā Pamata vai Modāls, Fāzes tur nebija paredzēts.  Vai modālo vajag atstāt? Vai fāzes vajag pielikt?

**Comment by lrituma** [comment]
Nezinu, kāpēc rakstīju, ka vajag pozīciju p. :D Vajag m vai o, tageris to paredz. Kļūdu sarakstā šobrīd izleca daži no plānā ledus, kur nebija iezīmēts kā modālais, domāju, ka viss izlabots.
