### ISSUE TITLE
"celties" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#56]
Tageris nepiedāvā (22.05.) atpazīt verbu "celties", tezaurā verbs ir ar visu tabulu (09.07.)

**Comment by PeterisP** [comment]
@lauma vai mēs varam tēzaurā no  https://tezaurs.lv/#/sv/celties izņemt norādi 'reti' ? Tas tak ir dikti populārs vārds; un 'reti' es lietoju kā marķieri lai izslēgtu absolūtas dīvainības, kurām tas 'reti' ir pielikts.

**Comment by lauma** [comment]
Es piekrītu. Pajautāšu.
