### ISSUE TITLE
"glābējs" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#57]
Tageris nemin lietvārdu. piedāvā verbu "glābēt" vai īpašības vārdu "glābējs".

**Comment by lauma** [comment]
Tēzaurā "glābējs" ir no kaut kādas bezgramatikas vārdnīcas. Es iesūtīju labojumos, kas jāpieliek, lai sanāktu paradigma.

**Comment by PeterisP** [comment]
Šķiet sen salabots.
