### ISSUE TITLE
"neesošs" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#58]
Tiek piedāvāts īpašības vārda tags, jo tezaurā tie tiek importēti kā īpašības vārdi (attiecas uz divdabjiem ar izskaņu -ošs, piemēram "ejošs"). Nepieciešama diskusija par prioritāšu secību tam, kā analizē šos vārdus - ka vispirms tiek piedāvāta verba tags, un īpašības vārda tags tikai tad, ja ir īpašā sarakstā.

**Comment by lrituma** [comment]
Tas varētu attiekties arī uz -ts un -ams divdabjiem un tezauru.

**Comment by PeterisP** [comment]
Nu, idejiski šķirkļa https://tezaurs.lv/#/sv/neeso%C5%A1s eksistence tieši nozīmē, ka viņš ir "īpašā sarakstā" kā atsevišķs, patstāvīgs īpašības vārds; un ja tam tā nav jābūt, tad tie šķirkļi būtu tēzaurā jāapvieno.

**Comment by lauma** [comment]
Nā, Tēzaurā ir daudz šādi sadalītu šķirkļu, mēs nevaram viņus tuvākā pusgada laikā visus apvienot.

**Comment by lauma** [comment]
Turklāt kā es jau esmu daudzkārt uzsvērusi, tad atšķirīgi šķirkļi nozīmē atšķirīgu semantiku (wsd), nevis atšķirīgu morfoloģiju.

**Comment by PeterisP** [comment]
@lrituma vai šī biļete ir sevi izsmēlusi ar neseno divdabjlietas diskusiju, vai arī tur vēl kaut kas jādara tieši ar neesošs?

**Comment by lrituma** [comment]
Nav aktuāli, atrisināts ar tēzaura divdabju, kuriem ir paradigma piešķirta, caurskatīšanu un sašķirošanu, kuri būs verbi un kuri nē.
