### ISSUE TITLE
Atgriezeniskie lietvārdi

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#6]
Tēzauram vajadzēs atgriezeniskajiem lietvārdiem atsevišķas paradigmas.

**-umies**

Loc. | Vienskaitlis | Daudzskaitlis
----- | ---------------- | ------------------
N. | vēlējumies | vēlējumies
Ģ. | - | -
D. | - | -
A. | vēlējumos | vēlējumos
L. | - | -

**-tājies, -tājās, -ējies, -ējās, -ājies**

Loc. | Vienskaitlis | Daudzskaitlis
----- | ---------------- | ------------------
N. | klausītājies, klausītājās | klausītājies, klausītājās
Ģ. | klausītājās,  klausītājās | klausītājos,  klausītājos
D. | - | -
A. | klausītājos,  klausītājos| klausītājos,  klausītājās
L. | - | -

**-šanās** - tas pats, kas iepriekšējā tabulā sieviešu dzimtē

Loc. | Vienskaitlis | Daudzskaitlis
----- | ---------------- | ------------------
N. | sarakstīšanās | sarakstīšanās
Ģ. | sarakstīšanās | sarakstīšanos
D. | - | -
A. | sarakstīšanos | sarakstīšanās
L. | - | -

Kopsavilkums - ir divi locīšanas "tipi" - sieviešu dzimtes (-ās) un vīriešu dzimtes (-ies) ar izņēmumumu, ka -umies nav ģenitīva, bet citiem -ies ir.

Neko, izņemot -šanās, neģenerēt automātiski, jo pārāk reti.

**Comment by PeterisP** [comment]
ājies ējies (pakaļdzinējies) un umies pielikti
