### ISSUE TITLE
"iesniedzējs" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#60]
Nepiedāvā lietvārda tagu, visticamāk tāpēc, ka tezaurā nav šķirkļa, bet galotne raksturīga īpašības vārdam. Iespējams vajag ierosināt Spektoram pievienot šo vārdu.

**Comment by PeterisP** [comment]
Ir interesants gļuks, ka uzmin ar nepareizu lemmu (iesniegējs). Jātestē un jālabo.

**Comment by PeterisP** [comment]
Nav aktuāls jo tēzaurā tagad ir paradigma

**Comment by VaBaiba** [comment]
NKK vienotā meklēšana: Vaicājumam "iesniegējs" atrasti 66 938 pieminējumi 13 no 28 korpusiem. 
Iespējams, ka uz jauno tageri tā vairs nebūs, bet pierakstu šeit, ka tagadējam tagerim ir šāda problēma.
