### ISSUE TITLE
"pāris" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#61]
Saistīts ar biļeti https://github.com/LUMII-AILab/Treebank/issues/150 .
Kaut arī vārdnīcas piedāvā tikai lietvārda šķirkli ar vienu no skaita nozīmēm, tomēr ņemot vērā lietojumu šajā nozīmē - nelokāmu formu -, mēs ar Guntu vienojāmies par homoformām - lokāms lietvārds "pāris" un advebrs "pāris", jo teikt, ka tajos lietojumos ir nominatīvs, ir vienkārši nesavietojami ar gramatisko sistēmu, savukārt teikt, ka ir divi "pāris" lietvārdi - viens lokāms un otrs nelokāms, ir pilnīgi pretēji mūsu centieniem tezaurā.

**Comment by lrituma** [comment]
Kaut arī sintaktiskās funkcijas nelokāmajai formai ir kā īpašības vārdam - tikai pie lietvārda, tomēr doma, ka lietvārda forma kļūst par nelokāmu īpašības vārdu liekas mazāk pieņemama, nekā doma, ka lievtārda nelokāma forma kļūst par adverbu, funkcijas kā adverbam "daudz" pie lietvārda.

**Comment by PeterisP** [comment]
Pašreiz skatos, ka ir lokāms lietvārds "pāris" tēzaurā un vēl nelokāms īpašības vārds "pāris" fiksētajā leksikonā.
@lrituma Vai tā ir ok? Tas nesaskan ar teikumu sākotnējā pieteikumā " mēs ar Guntu vienojāmies par homoformām - lokāms lietvārds "pāris" un advebrs "pāris"".  Ja jāmaina, saki kā.

**Comment by lrituma** [comment]
Šobrīd, 04.03.2021. domāju, ka pāris funkcionē līdzīgi kā daudz un vairāk pie lietvārda. Bet, atšķirībā no šiem vārdiem,  "pāris"nelieto kopā ar verbu adverba nozīmē, tāpēc tam nebūtu prātīgi dot adverba vārdšķiru. Ieliku Tēzaurā nelokāmu īpašības vārdu.

**Comment by PeterisP** [comment]
Korpusā ir ap 60 adverbisku "pāris" - 

pāris	r0q		(m-p9305-p3s4w13)
pāris        r0q		(m-p7773-p2s1w16)

**Comment by lrituma** [comment]
Saskāros ar to, ak piesaista ģenitīvu, un likās nedabiski tagad īpašības tagā krāmēt pazīmes dzimte, skaitlis, locījums pēc tā lietvārda, kam piesaistīts. Lai paliek par adverbu vienā grupā ar daudz, maz, cik un citiem zvēriem, kas piesaista ģenitīvu. tas nekas, ka ar verbu nelieto.
