### ISSUE TITLE
"spēlētājs" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#63]
Netiek piedāvāts lietvārda tags, tikai spēlētāt verba forma.

**Comment by lauma** [comment]
Es ieziņoju tēzauram, kāda gramatika te pieliekama.

**Comment by lrituma** [comment]
Tāpat "saldinātājs" piedāvā saldinātāt, vienīgais, kas ir tezaurā - saldinātāji, kuriem nav gramatika.

**Comment by lauma** [comment]
Saldinātājus nevar pārtaisīt šķirkli vienskaitlī? Tad varētu pielikt normālu pirmās 1. dekl. gramatiku.

**Comment by soshial** [comment]
Vārdu "spēlētājs" `Analyzer("Lexicon_v2.xml")` vispār neatpazina. Kas jādara?

**Comment by PeterisP** [comment]
Šķiet, ka sen salabots, gan spēlētājs, gan saldinātājs darbojas.
