### ISSUE TITLE
"toties" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#64]
"toties" tezauarā ir tikai adverbs, tageris piedāvā advera vai partikulas tagu, bet gan vecās, gan jaunās gramatikās tas ir arī homonīms normāls sakārtojuma saiklis jau sen, MLVV arī saka, ka saiklis. Jaunajā gramatikā viedoklis, ka tas apstākļa vārda funkcijas ir zaudējis un būtu vērtējams tikai kā sakārtojuma saiklis.

**Comment by lauma** [comment]
Tad uz MLVV pamata varētu T. arī ielikt informāciju par saikļa homonīmu.
