### ISSUE TITLE
Romiešu ciparu tags

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#65]
Kāpēc tageris piedāvā tikai pamata skaitļa vārda tagu xn, nevis arī kārtas skaitļa vārda tagu xo? (morfokļūdās III)

**Comment by PeterisP** [comment]
Man visiem romiešu cipariem ir šādi:
Vārdšķira="Reziduālis" Reziduāļa_tips="Skaitlis cipariem"

Var visādi, bet vajadzētu izlemt kā tad darīt (tikai kārtas? abus?) un tagset excelī iedokumentēt pie reziduāļu piemēriem arī romiešu ciparus

**Comment by PeterisP** [comment]
@lrituma vai šis vēl aktuāli?

**Comment by PeterisP** [comment]
Atstāts tags reziduālis-skaitlis cipariem, salikti 56. paradigmā 'Ar cipariem pierakstīti skaitļi (123, XVII)'
