### ISSUE TITLE
3. konjugācijas mijas

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#7]
No tēzaura 3. konjugācijas darbības vārdi nāks ar karodziņu par to, vai, salīdzinot tagadni un nenoteiksmi ir mija (saku/saki/saka pret sacīt) vai mijas nav (precu, preci, prec pret precēt). Būs vārdi, kam ir atzīstami abi varianti - gan ar miju, gan bez (ņurcīt, mocīt).

Izskaņām -ēt, -ēties šis karodziņš ietekmēs 1. un 3. personas veidošanu, bet 2. peronā mijas šiem nebūs neatkarīgi no karodziņa (sēžu/sēdi/sēž). Šobrīd šķiet, ka visos citos gadījumos pozitīva karodziņa gadījumā mija ir visās trijās personās.

Vajag tehnisko risinājumu, kas ļauj to atspoguļot leksikonā.

Izpratne par šo problēmu varbūt vēl tiks apdeitota, analizējot tālākos verbus.

**Comment by lauma** [comment]
Tikko atradu izņēmuma gadījuma izņēmuma gadījumu: sēdēt ir sēžu/sēdi/sēž - mijas 2. personā nav. Šobrīd vēl nesaprotu, ko ar to darīt.

**Comment by lauma** [comment]
Pašlaik izskatās, ka vārdi, kam ir izņēmums -ošs divdabja veidošanā ir tikai divi:
gulēt - guļošs, gulošs (pieļaujami abi)
sēdēt -  sēdošs (sēžošs būs nepareizi).

**Comment by PeterisP** [comment]
Gadījumiem ar miju ieviesta paradigma 45 parastajiem un 46 atgriezeniskajiem 3. konj verbiem.
