### ISSUE TITLE
e-paraksts, e-pakalpojums

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#74]
Tagotājs nepiedāvā lietvārda tagu, tezaurā ir e-paraksts bez gramatikas.

**Comment by lauma** [comment]
E-parakstam un e-pastam iesūtīju labojumu, kas pieliks gramatiku, e-pakalpjuma T. nemaz nav.

**Comment by PeterisP** [comment]
Šķiet sen salabots.
