### ISSUE TITLE
"pieskarties" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#75]
Tezaurā ir nepareiza paradigma pagātnē, tāpēc arī tagotājs nesaprot, ko piedāvā.

**Comment by lauma** [comment]
Ieziņoju.

**Comment by PeterisP** [comment]
@lauma tas joprojām https://tezaurs.lv/#/sv/pieskarties nepareizs, ko vēl varam tur darīt?

**Comment by lauma** [comment]
Nu, webā būs nepareizi, kamēr netiks ielādēta jauna Tēzaura versija, bet darba versijā ir jau pareizi, tikko apskatījos.

**Comment by PeterisP** [comment]
Šķiet sen salabots.
