### ISSUE TITLE
"apkārtējs" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#76]
Nezinu, kur šo likt - tezaurā ir "apkārtējs" bez gramatikas un "apkārtējais" ar gramatiku - loģiski, ka tageris piedāvā tikai ar noteikto galotni. Laikam prakse ir šādus tezaurā apvienot vienā šķirklī?

**Comment by lauma** [comment]
Mans vispārējais priekšstats būtu, ka vajag apvienot visu, kam nav liels, pamatīgs iemesls neapvienot. Te, manuprāt, nav tāda iemesla.

**Comment by PeterisP** [comment]
"apkārtējs" joprojām ir bez paradigmas un "apkārtējais" ir ar norādi, ka ir tikai noteiktā galotne.

@lrituma Vai šeit kaut kas vajadzīgs no morfoloģijas? Ja nav ok, tad drīzāk jālabo tēzaurā.

**Comment by lrituma** [comment]
Šķirkļi apvienoti, lemma ar nenoteikto galotni. Jāielabo korpusu datos.
