### ISSUE TITLE
"klusībā" tagošana

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#77]
ARī iespējams nevietā biļete - tezaurs saka, ka lietvārds, jo ir novecojusi nozīme vārdam "klusums", bet MLVV saka - klusībā ir apstākļa vārds, tātad jau sastingusi nelokāma forma. Es būtu par variantu, ka ir novecojis lietvārds un mūsdienu apstākļa vārds, korpusā ir samarķēts kā apstākļa vārds.

**Comment by PeterisP** [comment]
Tas drīzāk pie tēzaura datiem - https://tezaurs.lv/#/sv/klus%C4%ABba it kā īpaši norādīts "apst. nozīmē"; tad par tādiem vajag padomāt ka varbūt mums tādus "apst. nozīmē" vajag izķert un salikt kā apstākļa vārdus?

**Comment by lauma** [comment]
Jebkuru lietvārdu, kas nozīmē kaut vai kaut ko aptuveni līdzīgu laikam vai vietā, var lietot "apst. nozīmē", un čakls leksikogrāfs var iedomāties to šķirklī kā vēl vienu nozīmi paskaidrot. Tāpēc vien pataisīt tos visus par apstākļa vārdiem ir dublicējoši un neinformatīvi, tāpēc, imho, jālabo šis viens vārds, nevis visi masā.

**Comment by lauma** [comment]
Bet lai to ielabotu Tēzaurā, man vajag leksikogrāfu vai @vabaiba.

**Comment by lauma** [comment]
Baia saka, ka vajag 2 šķirkļus, apstākli un lietvārdu, tā kā ārs un ārā.

**Comment by PeterisP** [comment]
Šķiet sen salabots.
