### ISSUE TITLE
Izdalīt no 29 paradigmas (Hardcoded) stabilās grupas

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#8]
Nav loģiski, ka saikļiem un prievārdiem ir sava paradigma, bet izsauksmes vārdiem nav. Līdzīgi varētu izdalīt arī saīsinājumus un pieturzīmes, lai Hardcoded paliek tiešām galīgs nestandarts - trīsarpus utml.

**Comment by lauma** [comment]
Atvērts jautājums: vai savas paradigmu vajag arī ieiet/pāriet/uziet/apiet/noiet/paiet (tādi no Tēzaura var nākt) un būt/pabūt/nebūt/sabūt? Ja nē, tad šo biļeti ir laiks slēgt.

**Comment by PeterisP** [comment]
Kādu laiku jau ir ieviests:
36 : Saīsinājumi
37 : Pieturzīmes
38 : Izsauksmes vārdi
39 : Svešvalodu elementi
