### ISSUE TITLE
"pēdējais" un līdzīgo lemmas

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#80]
Biļetē https://github.com/LUMII-AILab/Morphocorpus/issues/9 Baiba nolēmusi, ka **pērnais, pēdējais, nākamais, pārējais, galvenais** lemmas būs ar noteikto galotni. Problēma, ka tezaurā visiem šiem vārdiem, izņemot **nākamais**, ir divi šķirkļi - viens ar nenoteiktu galotni, apvidvārdi, otrs ar noteiktu galotni. Tāpēc tageris piedāvā lemmu ar nenoteikto galotni. 
Datos izlaboju uz noteikto. Ja mēs rīkotos kā gadījumā ar "manējs, tavējs, savējs, jūsējs, mūsējs", tad būtu jāveido viens šķirklis ar apvidvārda pamatformu, tomēr toreiz lēmumu ietekmēja  šo nenoteikto formu lietošanas biežums. ŠAjā biļetā minētos vārdu pamatformas arī pēc manām domām jāatstāj ar noteikto galotni, jo tā viņus meklēs valodnieki, tādas formas viņiem ir arī MLVV.

**Comment by lauma** [comment]
Piefiksēju, ka mana valodas izjūta mulst, ka pie šiem ir nokļuvis arī _pērns_/_pērnais_.

**Comment by lrituma** [comment]
Pērns  - lemma pērns, tāds arī šķirklis. Valodnieki gan jau iedomāsies arī meklēt pērns, ja neatradīs pērnais. 
Pēdējais - lemma pēdējais, pēdējs ir novecojusi leksēma, apvienoti vienā šķirklī.
Nākamais - lemma ar noteikto galotni, cita šķirkļa nav.
Pārējais - lemma pārējais, pārējs ir novecojusi, apvienoti vienā šķirklī.
Galvenais - lemma galvenais, galvens ir novecojusi, apvienoti vienā šķirklī.

**Comment by PeterisP** [comment]
Manuprāt atrisināts savulaik ar 30. un 40. paradigmu ieviešanu, ja datos ir tās korekti saliktas.
