### ISSUE TITLE
Minētājam atvasinātāji galotnēm -tājs

### ISSUE THREAD

**Issue by PeterisP** [PeterisP/morphology#81]
Atbilstoši @lauma idejai #73 jāapdomā, kādos gadījumos latviešu valodā ir produktīvs -tājs atvasinājums - vai gadījumā, ja ieraugam kādu neatpazītu vārdu kas sagadīšanās pēc beidzas ar -tājs (vai visām pārējām locījumu formām) kuram ir pretī atbilstošs verba celms, vai varam pieņemt, ka tas ir no tā atvasināms?

No pirmā acu uzmetiena izskatās, ka visiem 2. un 3. konjugācijas tiešajiem darbības vārdiem šis darbojas :
- kārotājs
- jaudātājs
- tīkotājs
- nozīmētājs
- nevarētājs
- gribētājs
- drīkstētājs
- turpinātājs
- skolotājs
- mācītājs
daži no tiem ir reti vai nelietoti, bet ja nu kāds tā pateiks vai uzrakstīs, tad korekta interpretācija būtu to uztvert kā atvasinājumu.

Savukārt 1. konjugācijas verbiem izskatās ka nevienam nedarbojas -tājs, taču mēdz būt produktīvs -ējs:
- palicējs
- beidzējs
- pārstājējs
- atsācējs
- paguvējs

Ko valodnieki (@lrituma u.c.) par šo domā?

**Comment by PeterisP** [comment]
Issues #60 #69 #57 #48 principā reducējas uz šo - nevar rēķināties, ka visiem tiem atvasinājumiem būs patstāvīgs šķirklis vārdnīcā.

**Comment by PeterisP** [comment]
It kā ir risinājums, jāpatestē. Vēl vajadzētu pareizu terminu, kā šo atvasināšanu nosaukt; man ir deminutīvi un priedēkļi, bet šo nezinu kā saukt.

**Comment by lrituma** [comment]
**Derivāts** - vārds, kam ir atvasināts celms un kas ar vienu vai vairākiem afiksiem darināts no motivētājvārda, ar kuru tas saistīts nozīmes ziņā, piemēram, latviešu valodā no motivētājvārda gald-s ar priedēkli pa- un galotni -. atvasināts vārds pagalde. (termini)

**Comment by lrituma** [comment]
Derivāts ir tas, kas rodas vārddarināšanas rezultātā. Derivācijai ir dažādi vārddarināšanas viedi, kurus sauc kaut kā, atkarībā, kādas morfēmas izmantotas. Šis veids, kad pievieno piedēkli -tāj vai -ēj ir Sufiksācija. 
Ja derivātu veido ar priedēkli un piedēkli, tad būtu prefiksāli sufiksāls paņēmiens jeb konfiksācija. galva - ap-galv-o-t. Fleksācija - izmanto glotnes maiņu. ja tev vajag nosaukumu tieši tam, kas rodas atvasinājuma rezultātā, tad var lietot paņēmiena nosaukumu - **sufiksāls atvasinājums** - atvasinājums, kas veidots, pievienojot piedēkli.
