### ISSUE TITLE
Substantivizējušies īpašības vārdi sieviešu dzimtē

### ISSUE THREAD

**Issue by PeterisP** [PeterisP/morphology#82]
Šobrīd vārdiem kā https://tezaurs.lv/#/sv/n%C4%81kamais un https://tezaurs.lv/#/sv/galvenais ienākas 30. paradigma, kam ir tikai vīriešu dzimtes formas.

@lauma Vai mēs varam tādiem iedot arī 40. paradigmu, lai arī 'nākamā' un 'galvenā' darbojas no tēzaura info ? Bet tikai substantivizējušamies īpašības vārdiem, divdabjiem kā 'jaundzimušais' 40. paradigma būs fail un tur sieviešu dzimtes formas ir 41. paradigmā.

Es pagaidām pāris biežākajiem verbiem ieliku savā leksikonā, bet nu tas ir tāds aprisinājums.

**Comment by lauma** [comment]
Šķirklī "nākamais" ir jau alt lemmās ielikta lemma ar sieviešu dzimtes paradigmu un sieviešu dzimtes formu.

Atšķirt, kas ir substantivizējies un kas nav, tehniski nevar, un valodnieki arī vēl par katru instanci lauž šķēpus. Es lieku to alt lemmu klāt vienkārši visiem tiem noteikto galotņu šķirkļiem, kam tēzaurā ir dots galotņu šablonā, ka tā otra dzimte eksistē. Ja kādam nav dots, tad es nelieku. Un parastajiem īpašības/skaitļa vārdiem es nelieku, jo tiem jau morfoloģijas paradigma satur sieviešu dzimti.

Šķirklim "galvenais" tēzaurā nav bijis rakstīts, ka var būt sieviešu dzimte, aptaujāšos apkārt, vai  nevar to pierakstīt.
