### ISSUE TITLE
I.konj. verbu 2.personas galotnes

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#89]
Laura un Lauma grib izpētīt 1.konjugācijas verbu 2.personas tagadnes vienskaitļa galotņu lietojumu - kam liek un kam neliek galotni -i. 
Pēteri, ieliec lūdzu sarakstu, kuri verbi ir tajā sarakstā, kam liek galotni -i.
Vecajā gramatikā (1959) bija ieskicēta sistēma, kurām 1.konj. apakšgrupām liek -i, bet atbilstoši tajā gramaitkām aprakstītajām apakšgrupām. 
Trevora G. Fennela gramatikā arī ir norādes dažām 1.konj. apakšgrupām par šo jautājumu, piemēram, 132. lekcijā ir minēti "dental type (unvoiced)" , kuriem tagadnē celmā ir garš patskanis, bet nenoteiksmē un pagātnē īss, turklāt celms nenotieksmē beidzas ar s (kris-t), bet tagadnē un pagātnē šo s aizstāj t (krīt-u, krit-u), šim tipam 2.per. beidzas ar -i - krīti.
Labprāt atklātu sakarības, ja tādas pastāv.

**Comment by lauma** [comment]
Piemēram, tu krīti, klūpi, šķieti, dziesti, šķīsti, bet tu ēd, plēs, tēs, ver, sit, utt.

**Comment by PeterisP** [comment]
Pašreiz kodā to dara 7. mija, un -i tiek likts klāt tad ja

if (celms.endsWith("od") || celms.endsWith("ūd") || celms.endsWith("op") || celms.endsWith("ūp") || celms.endsWith("ot") || celms.endsWith("ūt") || celms.endsWith("īt") || celms.endsWith("st"))

**Comment by lauma** [comment]
Un jāņem vērā, ka pašlaik vēl nav izlabota #90 biļete, kas pieprasa uztaisīt formu _[tu] šķieti_.

**Comment by PeterisP** [comment]
jā, ar #90 nāk klāt || celms.endsWith("iet")

**Comment by PeterisP** [comment]
[ticket89.txt](https://github.com/PeterisP/morphology/files/7388671/ticket89.txt)
Saraksts ar esošajiem
