### ISSUE TITLE
Ģenitīveņi

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#9]
Hipotēze: vajag atdalīt ģenoitīveņus no lietvārdiem atsevišķā grupā (paradigmā) un uztvert līdzīgi kā nelokāmus īpašības vārdus.

Liekas, ka ģenitīvenis ne ar ko tekstā nesaskaņojas, tāpēc deklinācija, dzimte un skaitlis varētu izrādīties nebūtiskas un nevajadzīgas pazīmes. No otras puses, skaitļa un dzimtes zināšana palīdz ģenerēt vienskaitli/daudzskaitli, ja kādam tādu vajag.

No Tēzaura viedokļa: dzimtes noteikšana ģenitīvenim jāveic manuāli, vismaz daudzskaitļa gadījumā. Deklinācijas noteikšana lielākoties arī, tāpēc ģenitīveņu sīkāka neanalizēšana samazina roku darbu.

**Comment by lauma** [comment]
Tika nolemts, ka visiem vislabāk būs, ja ģenitīveņiem būs sava paradigma.
Šajā paradigmā ir jāievieto arī "milzu", "papildu" un "pagaidu", ko valodnieki jau ir sākuši tagot ar ģenitīveņa tagu `nc00gg` (lēmums te: https://github.com/LUMII-AILab/Treebank/issues/70 )

**Comment by PeterisP** [comment]
Paradigmas numurs būs 49.
