### ISSUE TITLE
nekārtnie verbu tekstu korpusos

### ISSUE THREAD

**Issue by GuntaN** [PeterisP/morphology#92]
Jāpanāk, lai lietotāji korpusos redzētu morfoloģiju, kurā _būt, dot, iet_ ar visiem atvasinājumiem būtu marķēti kā nekārtnie verbi, nevis 1. konjugācija.

**Comment by lauma** [comment]
Tēzaura transformators vārdiem _būt_ un _iet_ jau kopš laika gala lika, ka tie ir nekārtnie, tur ir kaut kādas zudības no tēzaura kaut kur uz priekšu.
_dot_ nekā īpatnēja locīšanā nav, viņam īsti to karodziņu neprasās, tāpēc visu laiku nebija, bet es tikko pieliku, turpmāk būs.

**Comment by lauma** [comment]
Tā, visās Tēzaura darba versijās tas tagad ir. Vajag tālāk uz morfo eksportēt.

**Comment by PeterisP** [comment]
Izskatās sen salabots.
