### ISSUE TITLE
32.paradigmā nav norādītas dzimtes

### ISSUE THREAD

**Issue by lrituma** [PeterisP/morphology#95]
Api parāda gan vīriešu dzimtes formas klausītājies nom. vsk un dsk., gan sieviešu dzimtes klausītājās nom. vsk, un dsk., bet dzimte nav pielikta šīm formām. Pārejās formas abām dzimtēm esot vienādas, tās, kas nu ir.

**Comment by PeterisP** [comment]
@lrituma varbūt mēs šos vārdus varam pielikt tēzaurā, lai man ir vismaz kādi praktiski testpiemēri šai paradigmai kā tas rādītos tēzaura tabulās nevis tīri morfoleksikonā?

**Comment by lauma** [comment]
Baigi regulārie atvasinājumi, droši vien tāpēc nav ielikti un grūti ielikt.
