### ISSUE TITLE
Vajag nošķirt paralēlformas no override

### ISSUE THREAD

**Issue by lauma** [PeterisP/morphology#97]
Vajag veidu, kā leksikonā norādīt, vai formas, ko dod hardcoded paradigmā, ir papildformas vai arī noteiktas formas aizstājējs. Piedāvātais karodziņš "Papildforma=Jā"

**Comment by PeterisP** [comment]
Risināsies ar https://gitlab.com/ailab/tezaurs/-/issues/365

**Comment by lauma** [comment]
2024-08-14 tika ieviests kodā, ka paralēlformas no override šķir.
